### ISSUE TITLE
MAKE ERROR

### ISSUE THREAD

**Issue by ykla** [LeChuckDE/open-ethereumclassic-pool#2]
github.com/yvasiyarov/go-metrics
github.com/yvasiyarov/newrelic_platform_go
github.com/yvasiyarov/gorelic
github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto
github.com/ethereum/ethash
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by LeChuckDE** [comment]
What should i read from a nothing saying log ?!?
Closed.... learn the basics ...

**Comment by ykla** [comment]
无日志

**Comment by ykla** [comment]
But that's all things output .There is not more logs to read.

**Comment by LeChuckDE** [comment]
there must be somewhere upwards to read which module failed to build. take a look which one and check if requirements are met. Pool compiles correctly on Ubuntu 16.04 LTS

**Comment by ykla** [comment]
My OS is ubuntu 16.04.2.
The required software dependencies are indeed installed.
