### ISSUE TITLE
Pending Balance... no payout?

### ISSUE THREAD

**Issue by Marow** [LeChuckDE/open-ethereumclassic-pool#3]
#### System information

Geth version: Version: 1.6.5-stable
Redis version: Redis server v=3.0.6
OS & Version: Linux Ubuntu 16.04

Hi, i have pending balance on my Account. But i dont know how to payout this "pending balance" to the miner... If i checked the coinbase balance in geth, i have it... 

I created also a "payouts.json" and a "unlocker.json" like your docs say. But nothing works. 
`No payees that have reached payout threshold`

Please help

**Comment by LeChuckDE** [comment]
Not an issue, only not able to read instructions.
1. Make sure you have unlocked your wallet with the parameters for geth or parity
2. Make sure you have configured the json files propper
3. Make sure your poolinstances are running for each function

If you struggle, there is also payed support for this.

**Comment by Marow** [comment]
Hi, kann ich dich vllt auf Deutsch fragen? Bist ja vermutlich Deutsch oder?

welchen geth Paramter meinst du? --unlock WALLET?
Configs sollten alle korrekt sein, das teil läuft ja und payouts und unlocker.json ebenfalls. Keine Errors oder so, einfach nur Infos das nichts auszuzahlen ist, was ja aber falsch ist.

Kannst du mir den "geth" Befehl einmal verraten, mit dem Payouts sowie mining usw funktionieren soll?

**Comment by LeChuckDE** [comment]
--unlock <eth.coinbase addresse> --password </path/to/password.file>
Zeig mal deine unlock.json und payout.json 
Show me please your unlock.json and payout.json
Pool URL ?

**Comment by Marow** [comment]
Unlocker.json
`{
        "redis": {
                "endpoint": "127.0.0.1:6379",
                "poolSize": 10,
                "database": 0,
                "password": ""
        },

        "unlocker": {
                "enabled": true,
                "poolFee": 0.15,
                "poolFeeAddress": "0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "donate": false,
                "depth": 32,
                "immatureDepth": 20,
                "keepTxFees": false,
                "interval": "10m",
                "daemon": "http://127.0.0.1:7656",
                "timeout": "10s"
        }
}
`
and payout.json
`{
        "redis": {
                "endpoint": "127.0.0.1:6379",
                "poolSize": 10,
                "database": 0,
                "password": ""
        },

        "payouts": {
                "enabled": true,
                "requirePeers": 25,
                "interval": "5m",
                "daemon": "http://127.0.0.1:7656",
                "timeout": "10s",
                //Coinbase Address
                "address": "0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 500000000,
                "bgsave": true
        }
}`

ohne --unlock und --password kann man nicht auszahlen? 

http://mine.house
Selbe System nur umgebaut für DBIX. Sollte aber daran nichts ändern. Der rest klappt ja auch, nur pending balance auf paid macht er nicht und zahlt nicht aus

**Comment by Marow** [comment]
Habe mal `personal.unlockAccount(eth.coinbase)` genutzt um während des betriebes unzulocken, aber geht nicht. Da kommt bei payouts.json (also wenn ich die ausführe) immer 
`2017/06/26 14:58:36 Backend check reply: PONG
2017/06/26 14:58:36 Starting block unlocker
2017/06/26 14:58:36 Set block unlock interval to 10m0s
2017/06/26 14:58:36 No block candidates to unlock
2017/06/26 14:58:37 No immature blocks to credit miners
`

**Comment by LeChuckDE** [comment]
config files are looking good, without unlocking of the wallet it isn't possible to payout anything, you should get error-message in payout-log about this...

please read the instructions carefully.

your are running the unlocker with this messages ... run payout processor ...

**Comment by Marow** [comment]
I do personal.unlockAccount(eth.coinbase) and it gives back true after login with passpharse.

But Payouts.json gives also back this message
    2017/06/26 14:58:28 Starting payouts
    2017/06/26 14:58:28 Set payouts interval to 5m0s
    2017/06/26 14:58:28 No payees that have reached payout threshold

**Comment by LeChuckDE** [comment]
have you also set this settings in all 3 json files to the same parameters ?

	"threads": 2,
	"coin": "etc",
	"name": "main",
